version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 23.x
    commands:
      - npm ci
  build:
    commands:
      - npm run build

artifacts:
  base-directory': 'dist'
  files: ['**/*']

cache:
  paths: ['node_modules/**/*']