version: 0.2
env:
  variables:
    NODE_ENV: "production"
    CI: "true"
phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - npm install --no-audit --no-fund --production --no-package-lock
  pre_build:
    commands:
      - |
        if [[ "$CODEBUILD_WEBHOOK_EVENT" =~ ^PULL_REQUEST_(CREATED|UPDATED|MERGED)$ ]]; then
          CHANGED_FILES=$(
            if [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_MERGED" ]; then
              git diff --name-only HEAD^1 HEAD
            else
              git diff --name-only origin/${CODEBUILD_WEBHOOK_BASE_REF} HEAD
            fi | grep '^src/' || true
          )
        
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changes in src directory, skipping build"
            exit 0
          fi
          echo "$CHANGED_FILES" > changed_files.txt
        else
          echo "Not a PR event, skipping"
          exit 0
        fi
  build:
    commands:
      - |
        if [ -s changed_files.txt ]; then
          xargs -P 2 -I {} npm run build -- --file {} < changed_files.txt
        fi

artifacts:
  base-directory: 'dist'
  files:
    - '**/*'
  name: '' # This ensures no prefix is added
  discard-paths: false # Keep the directory structure from dist
  when:
    - CODEBUILD_WEBHOOK_EVENT = "PULL_REQUEST_MERGED"

