version: 0.2
env:
  variables:
    NODE_ENV: "production"
    CI: "true"
phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - npm install --no-audit --no-fund --production --no-package-lock
  pre_build:
    commands:
      - |
        if [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_CREATED" ] || [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_UPDATED" ]; then
          echo "Processing Pull Request"
          git fetch origin ${CODEBUILD_WEBHOOK_BASE_REF#refs/heads/}
          CHANGED_FILES=$(git diff --name-only FETCH_HEAD HEAD | grep '^src/' || true)
          echo "$CHANGED_FILES" > changed_files.txt
        elif [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_MERGED" ]; then
          echo "Processing Merged PR"
          # Get the merge commit's parents
          MERGE_BASE=$(git merge-base HEAD^ HEAD)
          CHANGED_FILES=$(git diff --name-only $MERGE_BASE HEAD | grep '^src/' || true)
          echo "$CHANGED_FILES" > changed_files.txt
        else
          echo "Not a PR event, skipping"
          echo "Event type: $CODEBUILD_WEBHOOK_EVENT"
          exit 0
        fi
  
        if [ -z "$CHANGED_FILES" ]; then
          echo "No changes in src directory, skipping build"
          exit 0
        fi

        # Debug information
        echo "Base ref: $CODEBUILD_WEBHOOK_BASE_REF"
        echo "Head ref: $CODEBUILD_WEBHOOK_HEAD_REF"
        echo "Changed files:"
        echo "$CHANGED_FILES"

  build:
    commands:
      - |
        if [ -s changed_files.txt ]; then
          if [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_CREATED" ] || [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_UPDATED" ]; then
            xargs -P 2 -I {} npm run build -- --file {} --dryrun < changed_files.txt
          elif [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_MERGED" ]; then
            xargs -P 2 -I {} npm run build -- --file {} < changed_files.txt
          fi
        fi

  post_build:
    commands:
      - |
        if [ "$CODEBUILD_WEBHOOK_EVENT" != "PULL_REQUEST_MERGED" ]; then
          mkdir -p dist
          touch dist/.placeholder
          echo "Will not upload artifacts, skipping and exiting successfully"
          exit 0
        fi

artifacts:
  base-directory: dist
  files:
    - '**/*'
  name: ''
  discard-paths: no

