name: Sync dist Folder to S3

on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_REGION: "us-east-1"
  S3_BUCKET: "fdo-plugins"
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

jobs:
  publish-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'src/**'
          list-files: 'shell'

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-S3

      - run: npm ci
      - run:
          |
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            npm run build -- --event push --file ${SRC}_files
          else
            npm run build --file ${SRC}_files
          fi
